### ISSUE TITLE
Help: How to completely replace types/interfaces

### ISSUE THREAD

**Issue by domarmstrong** [AEB-labs/graphql-weaver#12]
My case is that I have some common types and interfaces between apis. But when trying to merge the schemas I get `schema must contain unique named types but contains multiple types named "Node"` for example, which makes sense. I've been trying to replace the common types with a local value, so all 'node' usage in each api uses local 'node' type.

I've tried the transformSchema method, which works to a point but it looks like you need to replace the field types also with this new type, which would then involve descending through non null lists etc to find the type to replace also.

Am I missing something, is there a simpler way?

**Comment by adamkl** [comment]
If I understand your issue correctly, I think you should just be able to use the `typePrefix` option. This will prefix all types in a given schema to resolve any conflicts between schemas.
```javascript
const schema: GraphQLSchema = await weaveSchemas({
    endpoints: [{
        namespace: 'model',
        typePrefix: 'Model', // <--- *use this*
        url: 'http://localhost:8080/graphql' 
    }, {
        namespace: 'local',
        schema: new GraphQLSchema(/* ... */) 
    }]
})
```

**Comment by domarmstrong** [comment]
Sure I can but then I would have things like:

ISO8601Date
OTHER_ISO8601DATE
ANOTHER_ISO8601DATE

Which is horrible. I'd prefer to resolve all ISO8601DATE scalars to be the same type if I can.

**Comment by adamkl** [comment]
Ok, now I understand.. Yes, that would be horrible. 

The error is coming from graphql itself because there are [duplicate type entries in the schema TypeMap](https://github.com/graphql/graphql-js/blob/36b3407c2509822edd5762ffcdef7ac3d56d15d4/src/type/schema.js#L244). 

It looks like the [`Transformer`](https://github.com/AEB-labs/graphql-weaver/blob/e652e66b75ec443fbf61f52db70f93b414731704/src/graphql/schema-transformer.ts#L191) is responsible for creating the new TypeMap (its called by `transformSchema`), but the `SchemaTransformer` you pass in doesn't have access to the entire TypeMap, so it can't perform deduplication. 

It might be necessary to change `Transformer` to perform deduplication, or to change how it interacts with SchemaTransformer to allow access to the TypeMap so that a pipeline module can perform the deduplication.

@Yogu , @henkesn, what do you guys think? You're the experts.

**Comment by Yogu** [comment]
You can transform the schema in two places, the two *pipelines* rows:

```
           +------+  +------+  +------+
Endpoints  |Schema|  |Schema|  |Schema|
           +------+  +------+  +------+

           +------+  +------+  +------+
            X    X    X    X    X    X
Pipelines    X  X      X  X      X  X
              XX        XX        XX

               +                  +
Merge           +----------------+

                     +------+
                      X    X
Pipeline               X  X
                        XX

                     +------+
Server               |Schema|
                     +------+
```

The collision occurs in the *merge* step, so you can't use the second pipeline to do the fix. In the first pipeline, you only have access to one endpoint (schema). This leaves you with two options:

* Create a new, canonical `ISO8601Date` type (`new GraphQLObjectType(...)`) and use that in place of the old types. To do the replacement, you can write a transformer that changes every occurrance of an `ISO8601Date` type by the canonical one.
* Fetch one schema and extract the canonical type from it before calling `weaveSchemas`, then use the same transformer.

The transformation module could look like this:

```typescript
class MyModule implements PipelineModule {
    transformExtendedSchema(schema: ExtendedSchema): ExtendedSchema {
        return transformedSchema = transformExtendedSchema(schema, {
            transformField(field: GraphQLNamedFieldConfig<any, any>, context) {
                if (field.type.name == 'ISO8601Date') {
                    return {
                        ...field,
                        type: canonicalDateType
                    };
                }
                return field;
            }
        });
    }
}`

See the [README](https://github.com/AEB-labs/graphql-weaver#custom-transformations) on how to activate this module.

**Comment by Yogu** [comment]
Related to #13, where this manual way using PreMergeModules would be pretty inconvenient.

**Comment by domarmstrong** [comment]
Closing as stale and no longer needed
