### ISSUE TITLE
Misbehavior for scalar type , maybe an edge case ?

### ISSUE THREAD

**Issue by gengjiawen** [AEB-labs/graphql-weaver#20]
Is the parse function meant to filter null or undefined value ? If that's the case, when the value is number 0, the returned value will be false.
https://github.com/AEB-labs/graphql-weaver/blob/0885029c0a12ba292f81e59a6db3f1b6b00003b5/src/pipeline/custom-scalar-types-serialization.ts#L28-L31

**Comment by gengjiawen** [comment]
And also maybe we need to deal with empty string too since empty string also is false.

**Comment by Yogu** [comment]
You're right, it seems like we forgot those cases there. I'll try to look into it in the next few days. Of course, you're also welcome to submit a PR with a failing test or a fix.

**Comment by gengjiawen** [comment]
Is it okay change to this ?
```typescript
function parseValue(value: any) {
    return value;
}
```

**Comment by Yogu** [comment]
@henkesn Do you remember why you added the `|| false`? In any case, we should add some regression tests.

**Comment by Yogu** [comment]
@gengjiawen Thanks again for the bug report. We just released 0.11.4, please let us know if this does not fix your problem.
