### ISSUE TITLE
Question: how to forward the origin extra http header ?

### ISSUE THREAD

**Issue by gengjiawen** [AEB-labs/graphql-weaver#6]
I need to pass the token to the server in my situation.

**Comment by Yogu** [comment]
Good question, we faced this use case, too.

You can pass a custom [`GraphQLClient`](https://github.com/AEB-labs/graphql-weaver/blob/master/src/graphql-client/graphql-client.ts) instance for endpoints to completely customize how data is fetched. In your situation, I'd suggest to extend [`HttpGraphQLClient`](https://github.com/AEB-labs/graphql-weaver/blob/master/src/graphql-client/http-client.ts):

```typescript
class AuthForwardingGraphQLClient extends HttpGraphQLClient {
        protected async getHeaders(document: DocumentNode, variables?: { [name: string]: any }, context?: any, introspect?: boolean): Promise<{ [index: string]: string }> {
            const headers = await super.getHeaders(document, context, introspect);
        return {
            ...headers,
            Authentication: getAuthTokenFromGraphQLContext(context)
        };
    }
}

const schema: GraphQLSchema = await weaveSchemas({
    endpoints: [{
        namespace: 'library',
        client: AuthForwardingGraphQLClient('http://example.com/graphql')
    }]
});
```

Then, you somehow need to implement `getAuthTokenFromGraphQLContext`. How this is done depends on your GraphQL server implementation. If you use express-graphql, [the express Request object is passed as context, by default](https://github.com/graphql/express-graphql#options). Then, something like this would do the job:

```typescript
function getAuthTokenFromGraphQLContext(context: any) {
    return context.header('Authentication');
}
```

**Comment by gengjiawen** [comment]
I followed your advice , but I still can't make it work, this is the demo code https://github.com/gengjiawen/schema-stitching-demo/tree/feature/pass_header, can you take a look ? thanks

**Comment by Yogu** [comment]
Sorry, I confused `Authentication` and `Authorization`. Also, express seems to convert the header names to lower case for some reason. I tested it locally and it at least dumped the correct token, though I did not test it with a real auth token. See [this pull request in your project](https://github.com/gengjiawen/schema-stitching-demo/pull/1/files) for the changes.

**Comment by gengjiawen** [comment]
thanks, I will give it a try tomorrow.

**Comment by gengjiawen** [comment]
It works like as expected now, thanks. But why when i first running, I got log looks like this?
```
pass undefined
pass undefined
not valid undefined
not valid undefined
```

**Comment by gengjiawen** [comment]
I see, that's because that time express-graphql is not used. Thanks for your great patience and help.

**Comment by gengjiawen** [comment]
For anyone want to pass all the original headers, you can do something like this:
Notice to remove `content-length` from original header, or you will get timeout exception. This is found by @FX-HAO
```ts
class AuthForwardingGraphQLClient extends HttpGraphQLClient {
  protected async getHeaders(document: DocumentNode, variables?: { [name: string]: any }, context?: any, introspect?: boolean): Promise<{ [index: string]: string }> {
    const headers = await super.getHeaders(document, context, introspect);
    console.log('headers', headers)
    if (context) {
      console.log('context headers', context.headers)
      delete context.headers['content-length']
      return context.headers
    } else {
      return headers
    }
  }
}
```

**Comment by adamkl** [comment]
Hey Yogu, I was just working on this exact scenario last week and came up with pretty much the same solution you suggested. 
It was very easy to take a look at your code to see how it could be extended. You guys did a great job with the design and API!
