### ISSUE TITLE
Weaved schema doesn't include type descriptions

### ISSUE THREAD

**Issue by adamkl** [AEB-labs/graphql-weaver#7]
I just spent a little time updating the type descriptions on one of by back-end graphql services and I noticed that these descriptions don't appear to be displayed in the weaved schema on my gateway server. 

I'm looking to provide a self serve graphql API to my consumers so these type descriptions would be pretty valuable. 

I'm going to see if I can get some time to work on this myself if you're open to pull requests.

**Comment by Yogu** [comment]
Thanks for the bug report. The most obvious source would be if I forgot it [here](https://github.com/AEB-labs/graphql-weaver/blob/a838f5a2863a7397cd74c733de08c604eb4cb2de/src/graphql/schema-transformer.ts#L340), but that's not the case. I don't know where else the problem could be. I'll see if I have time to try to reproduce the bug in the next days. If you have the time, we are definitely open for pull requests. 🎉

**Comment by adamkl** [comment]
I'll double and triple check on my end to make sure I'm not wasting your time.

**Comment by Yogu** [comment]
It might very well be a bug, there are some other places where type configs
are partially changed. Maybe you can check for which kind of types it
applies? E. g. The root query type, normal types, such types involved in
link/join, or all of them?

**Comment by adamkl** [comment]
Before anyone else wastes any time looking into this, with my latest config/deploy, I can see that the descriptions are being weaved correctly. 

I removed the namespace/typePrefix from my configuration and the descriptions appeared. I'm going to play around a bit more to see if I can repro the issue.

**Comment by adamkl** [comment]
I haven't been able to repo this. You should probably close this one.
